/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import operationsapp.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author matheus
 */
public class GUIHome extends javax.swing.JFrame {

    /**
     * Creates new form GUIHome
     */
    public GUIHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmAddChar = new javax.swing.JDialog();
        buttonConfirmAddChar = new javax.swing.JButton();
        buttonCancelAddChar = new javax.swing.JButton();
        textChargeConfirm = new javax.swing.JLabel();
        confirmAddRev = new javax.swing.JDialog();
        buttonConfrmAddRev = new javax.swing.JButton();
        buttonCancelAddRev = new javax.swing.JButton();
        textRevenueConfirm = new javax.swing.JLabel();
        moreInformation = new javax.swing.JDialog();
        labelMoreAddValue = new javax.swing.JLabel();
        moreAddValue = new javax.swing.JTextField();
        labeMoreAddDate = new javax.swing.JLabel();
        moreAddDate = new javax.swing.JTextField();
        labelMoreCateg = new javax.swing.JLabel();
        selectMoreCategory = new javax.swing.JComboBox<>();
        labelMoreDesc = new javax.swing.JLabel();
        textMoreDesc = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonMoreAdd1 = new javax.swing.JButton();
        buttonMoreCancel = new javax.swing.JButton();
        radioButtonMoreChar = new javax.swing.JRadioButton();
        radioButtonMoreRev = new javax.swing.JRadioButton();
        buttonGroupMoreInf = new javax.swing.ButtonGroup();
        panelInf = new javax.swing.JTabbedPane();
        panelExtract = new javax.swing.JPanel();
        labelChaRev = new javax.swing.JLabel();
        listExtract = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        separatorExtract = new javax.swing.JSeparator();
        labelBalance = new javax.swing.JLabel();
        valueBalance = new javax.swing.JLabel();
        panelReport = new javax.swing.JPanel();
        panelAdd = new javax.swing.JPanel();
        try {
            addValue =(javax.swing.JTextField)java.beans.Beans.instantiate(getClass().getClassLoader(), "GUI.GUIHome_addValue");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        labelDate = new javax.swing.JLabel();
        labelValue = new javax.swing.JLabel();
        buttonAddCharge = new javax.swing.JButton();
        addDate = new javax.swing.JTextField();
        buttonAddRevenue = new javax.swing.JButton();
        buttonMoreInformation = new javax.swing.JButton();
        categoryAdd = new javax.swing.JComboBox<>();
        labelCategory = new javax.swing.JLabel();

        confirmAddChar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        confirmAddChar.setResizable(false);
        confirmAddChar.setType(java.awt.Window.Type.UTILITY);

        buttonConfirmAddChar.setText("Salvar");

        buttonCancelAddChar.setText("Cancelar");

        textChargeConfirm.setText("jLabel6");

        javax.swing.GroupLayout confirmAddCharLayout = new javax.swing.GroupLayout(confirmAddChar.getContentPane());
        confirmAddChar.getContentPane().setLayout(confirmAddCharLayout);
        confirmAddCharLayout.setHorizontalGroup(
            confirmAddCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmAddCharLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmAddCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmAddCharLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addComponent(buttonCancelAddChar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonConfirmAddChar))
                    .addComponent(textChargeConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        confirmAddCharLayout.setVerticalGroup(
            confirmAddCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmAddCharLayout.createSequentialGroup()
                .addComponent(textChargeConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confirmAddCharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonConfirmAddChar)
                    .addComponent(buttonCancelAddChar))
                .addContainerGap())
        );

        confirmAddRev.setResizable(false);
        confirmAddRev.setType(java.awt.Window.Type.UTILITY);

        buttonConfrmAddRev.setText("Salvar");

        buttonCancelAddRev.setText("Cancelar");
        buttonCancelAddRev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelAddRevActionPerformed(evt);
            }
        });

        textRevenueConfirm.setText("jLabel7");

        javax.swing.GroupLayout confirmAddRevLayout = new javax.swing.GroupLayout(confirmAddRev.getContentPane());
        confirmAddRev.getContentPane().setLayout(confirmAddRevLayout);
        confirmAddRevLayout.setHorizontalGroup(
            confirmAddRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmAddRevLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confirmAddRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textRevenueConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmAddRevLayout.createSequentialGroup()
                        .addGap(0, 54, Short.MAX_VALUE)
                        .addComponent(buttonCancelAddRev)
                        .addGap(5, 5, 5)
                        .addComponent(buttonConfrmAddRev)))
                .addContainerGap())
        );
        confirmAddRevLayout.setVerticalGroup(
            confirmAddRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, confirmAddRevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textRevenueConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(confirmAddRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelAddRev)
                    .addComponent(buttonConfrmAddRev))
                .addContainerGap())
        );

        labelMoreAddValue.setText("Valor");

        moreAddValue.setText("jTextField1");

        labeMoreAddDate.setText("Data");

        moreAddDate.setText("jTextField1");

        labelMoreCateg.setText("Categoria");

        selectMoreCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelMoreDesc.setText("Descrição");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        textMoreDesc.setViewportView(jTextArea1);

        buttonMoreAdd1.setText("Salvar");

        buttonMoreCancel.setText("Cancelar");

        buttonGroupMoreInf.add(radioButtonMoreChar);
        radioButtonMoreChar.setText("Despesa");

        buttonGroupMoreInf.add(radioButtonMoreRev);
        radioButtonMoreRev.setText("Receita");

        javax.swing.GroupLayout moreInformationLayout = new javax.swing.GroupLayout(moreInformation.getContentPane());
        moreInformation.getContentPane().setLayout(moreInformationLayout);
        moreInformationLayout.setHorizontalGroup(
            moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moreInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectMoreCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textMoreDesc)
                    .addGroup(moreInformationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonMoreCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonMoreAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(moreInformationLayout.createSequentialGroup()
                        .addGroup(moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moreInformationLayout.createSequentialGroup()
                                .addComponent(labelMoreAddValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moreAddValue, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labeMoreAddDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moreAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelMoreCateg)
                            .addComponent(labelMoreDesc)
                            .addGroup(moreInformationLayout.createSequentialGroup()
                                .addComponent(radioButtonMoreChar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radioButtonMoreRev)))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap())
        );
        moreInformationLayout.setVerticalGroup(
            moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moreInformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMoreAddValue)
                    .addComponent(moreAddValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labeMoreAddDate)
                    .addComponent(moreAddDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonMoreChar)
                    .addComponent(radioButtonMoreRev))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMoreCateg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectMoreCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMoreDesc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMoreDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(moreInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonMoreAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMoreCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        labelChaRev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelChaRev.setText("Custos e Receitas:");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listExtract.setViewportView(jList2);

        labelBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelBalance.setText("Saldo");

        valueBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valueBalance.setText("R$");

        javax.swing.GroupLayout panelExtractLayout = new javax.swing.GroupLayout(panelExtract);
        panelExtract.setLayout(panelExtractLayout);
        panelExtractLayout.setHorizontalGroup(
            panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(valueBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelChaRev, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(listExtract, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorExtract, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBalance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelExtractLayout.setVerticalGroup(
            panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelChaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorExtract, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelInf.addTab("Extrato", panelExtract);

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 244, Short.MAX_VALUE)
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        panelInf.addTab("Relatorios", panelReport);

        addValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addValueActionPerformed(evt);
            }
        });

        labelDate.setText("Data");

        labelValue.setText("Valor");

        buttonAddCharge.setBackground(new java.awt.Color(255, 102, 102));
        buttonAddCharge.setText("Adicionar Custo");
        buttonAddCharge.setBorder(null);
        buttonAddCharge.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDateActionPerformed(evt);
            }
        });

        buttonAddRevenue.setBackground(new java.awt.Color(102, 255, 102));
        buttonAddRevenue.setText("Adicionar Receita");
        buttonAddRevenue.setBorder(null);
        buttonAddRevenue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonMoreInformation.setForeground(new java.awt.Color(0, 0, 204));
        buttonMoreInformation.setText("Mais Informações");
        buttonMoreInformation.setBorderPainted(false);
        buttonMoreInformation.setContentAreaFilled(false);
        buttonMoreInformation.setFocusPainted(false);
        buttonMoreInformation.setMargin(new java.awt.Insets(0, 0, 0, 0));

        categoryAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryAddActionPerformed(evt);
            }
        });

        labelCategory.setText("Categoria");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(categoryAdd, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddLayout.createSequentialGroup()
                            .addComponent(buttonAddCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonAddRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(addDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addValue, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(buttonMoreInformation)
                    .addComponent(labelCategory))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAddLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelDate)
                    .addContainerGap(205, Short.MAX_VALUE)))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addValue, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(labelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMoreInformation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelAddLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(labelDate)
                    .addContainerGap(310, Short.MAX_VALUE)))
        );

        addValue= maskValue(60,  "0,1,2,3,4,5,6,7,8,9");
        buttonAddCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddChar.setSize(300,150);
                confirmAddChar.setVisible(true);
            }
        });
        try {
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            addDate = new javax.swing.JFormattedTextField(data); }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro }
    }
    buttonAddRevenue.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            confirmAddRev.setSize(300,150);
            confirmAddRev.setVisible(true);
        }
    });
    buttonMoreInformation.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            moreInformation.setSize(350,380);
            moreInformation.setVisible(true);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(panelInf)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(panelInf)
        .addGroup(layout.createSequentialGroup()
            .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    setSize(new java.awt.Dimension(523, 374));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelAddRevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelAddRevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelAddRevActionPerformed
   
    private void addDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addDateActionPerformed

    private void addValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addValueActionPerformed

    private void categoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHome().setVisible(true);
            }
        });
    }
public JTextField maskValue(int tamanho,String caracteres) { 
    try { 
        String quantidade="";
        for(int i=0 ; i < tamanho; i++){
            quantidade=quantidade+"#";
        }
        javax.swing.text.MaskFormatter nome=new javax.swing.text.MaskFormatter(quantidade);
        nome.setValidCharacters(caracteres);
        return new javax.swing.JFormattedTextField(nome);}
    catch(Exception e){
        JOptionPane.showMessageDialog(null,"Ocorreu um erro");
        return new JTextField();
    }
}


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addDate;
    private javax.swing.JTextField addValue;
    private javax.swing.JButton buttonAddCharge;
    private javax.swing.JButton buttonAddRevenue;
    private javax.swing.JButton buttonCancelAddChar;
    private javax.swing.JButton buttonCancelAddRev;
    private javax.swing.JButton buttonConfirmAddChar;
    private javax.swing.JButton buttonConfrmAddRev;
    private javax.swing.ButtonGroup buttonGroupMoreInf;
    private javax.swing.JButton buttonMoreAdd1;
    private javax.swing.JButton buttonMoreCancel;
    private javax.swing.JButton buttonMoreInformation;
    private javax.swing.JComboBox<String> categoryAdd;
    private javax.swing.JDialog confirmAddChar;
    private javax.swing.JDialog confirmAddRev;
    private javax.swing.JList<String> jList2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeMoreAddDate;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelChaRev;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelMoreAddValue;
    private javax.swing.JLabel labelMoreCateg;
    private javax.swing.JLabel labelMoreDesc;
    private javax.swing.JLabel labelValue;
    private javax.swing.JScrollPane listExtract;
    private javax.swing.JTextField moreAddDate;
    private javax.swing.JTextField moreAddValue;
    private javax.swing.JDialog moreInformation;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelExtract;
    private javax.swing.JTabbedPane panelInf;
    private javax.swing.JPanel panelReport;
    private javax.swing.JRadioButton radioButtonMoreChar;
    private javax.swing.JRadioButton radioButtonMoreRev;
    private javax.swing.JComboBox<String> selectMoreCategory;
    private javax.swing.JSeparator separatorExtract;
    private javax.swing.JLabel textChargeConfirm;
    private javax.swing.JScrollPane textMoreDesc;
    private javax.swing.JLabel textRevenueConfirm;
    private javax.swing.JLabel valueBalance;
    // End of variables declaration//GEN-END:variables
}
