/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
 * @author Matheus Soares
 */
package GUI;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import operationsapp.*;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author matheus
 */
public class GUIHome extends javax.swing.JFrame {

    /**
     * Creates new form GUIHome
     */
    public GUIHome() {
        initComponents();
        user = new User();
        ////////////////////////////////////////////////////////////////////
        ////////////////////TESTE/////////////////////////////////////
        /////////////////////////////////////////////////////////////////
        AddTestes testes = new AddTestes(user);
        for(int i=0;i<testes.getStrings().size();i++)
                updateListExt(testes.getStrings(i));
        balanceUpdate();
        ////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////*/
        id=0;
        listRevenueCategory = listRevCatCri();
        listChargeCategory = listCharCatCri();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHome().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupMoreInf = new javax.swing.ButtonGroup();
        expFilExp = new javax.swing.JFileChooser();
        buttonGroupAdd = new javax.swing.ButtonGroup();
        buttonGroupFiltExt = new javax.swing.ButtonGroup();
        buttonGroupFiltGra = new javax.swing.ButtonGroup();
        panelInf = new javax.swing.JTabbedPane();
        panelExtract = new javax.swing.JPanel();
        labelChaRev = new javax.swing.JLabel();
        separatorExtract = new javax.swing.JSeparator();
        labelBalance = new javax.swing.JLabel();
        valueBalance = new javax.swing.JLabel();
        PanelFiltExtr = new javax.swing.JPanel();
        checkCharExtFilt = new javax.swing.JCheckBox();
        chekRevExtFilt = new javax.swing.JCheckBox();
        checDateExtFilt = new javax.swing.JCheckBox();
        texDateFromExtFilt = new javax.swing.JTextField();
        labeDateSepExtFilt = new javax.swing.JLabel();
        texDateUntilExtFilt = new javax.swing.JTextField();
        buttonSelecExtFilt = new javax.swing.JButton();
        PanelShowExtract = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExtract = new javax.swing.JTable();
        panelReport = new javax.swing.JPanel();
        panelAnualGraph = new javax.swing.JPanel();
        labelGrapAnual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PanelFiltExtr1 = new javax.swing.JPanel();
        checkCharGraFilt = new javax.swing.JCheckBox();
        chekRevGraFilt = new javax.swing.JCheckBox();
        checDateGraFilt = new javax.swing.JCheckBox();
        texDateFromGraFilt = new javax.swing.JTextField();
        labeDateSepGraFilt = new javax.swing.JLabel();
        texDateUntilGraFilt = new javax.swing.JTextField();
        buttonSelecGraFilt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelAdd = new javax.swing.JPanel();
        labelDate = new javax.swing.JLabel();
        labelValue = new javax.swing.JLabel();
        addValue = new javax.swing.JTextField();
        selectCategory = new javax.swing.JComboBox<>();
        buttonAdd = new javax.swing.JButton();
        radioButtonCharge = new javax.swing.JRadioButton();
        radioButtonRevenue = new javax.swing.JRadioButton();
        labelCategory = new javax.swing.JLabel();
        addDate = new javax.swing.JTextField();
        addTitle = new javax.swing.JTextField();
        labelTitle = new javax.swing.JLabel();
        buttonExp = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        expFilExp.setAcceptAllFileFilterUsed(false);
        expFilExp.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        panelInf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelInfFocusGained(evt);
            }
        });

        labelChaRev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelChaRev.setText("Extrato");

        labelBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelBalance.setText("Saldo");

        valueBalance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        buttonGroupFiltExt.add(checkCharExtFilt);
        checkCharExtFilt.setText("Despesas");

        buttonGroupFiltExt.add(chekRevExtFilt);
        chekRevExtFilt.setText("Receitas");

        texDateFromExtFilt.setEnabled(false);

        labeDateSepExtFilt.setText("-");

        texDateUntilExtFilt.setEnabled(false);

        buttonSelecExtFilt.setText("Filtro");

        javax.swing.GroupLayout PanelFiltExtrLayout = new javax.swing.GroupLayout(PanelFiltExtr);
        PanelFiltExtr.setLayout(PanelFiltExtrLayout);
        PanelFiltExtrLayout.setHorizontalGroup(
            PanelFiltExtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltExtrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkCharExtFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chekRevExtFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checDateExtFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texDateFromExtFilt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeDateSepExtFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texDateUntilExtFilt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSelecExtFilt)
                .addContainerGap())
        );
        PanelFiltExtrLayout.setVerticalGroup(
            PanelFiltExtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltExtrLayout.createSequentialGroup()
                .addGroup(PanelFiltExtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFiltExtrLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(PanelFiltExtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkCharExtFilt)
                            .addComponent(chekRevExtFilt)
                            .addComponent(checDateExtFilt)))
                    .addGroup(PanelFiltExtrLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelFiltExtrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texDateFromExtFilt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labeDateSepExtFilt)
                            .addComponent(texDateUntilExtFilt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSelecExtFilt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checDateExtFilt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(checDateExtFilt.isSelected()){
                    texDateFromExtFilt.setEnabled(true);
                    texDateUntilExtFilt.setEnabled(true);
                }
                else{
                    texDateFromExtFilt.setEnabled(false);
                    texDateUntilExtFilt.setEnabled(false);
                }
            }
        });
        buttonSelecExtFilt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(checkCharExtFilt.isSelected()){
                    if(checDateExtFilt.isSelected()){
                        filtExtChargDate();
                    }else{
                        filtExtCharg();
                    }
                }else{
                    if(chekRevExtFilt.isSelected()){
                        if(checDateExtFilt.isSelected()){
                            filtExtRevDate();
                        }else{
                            filtExtRev();
                        }
                    }else{
                        if(checDateExtFilt.isSelected()){
                            filtExtDate();
                        }else{
                            JOptionPane.showMessageDialog(null, "Selecione um filtro!");
                        }
                    }
                }
            }
        });

        tableExtract.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Categoria", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableExtract);
        tableExtract.getColumnModel().getColumn(0).setPreferredWidth(200);
        tableExtract.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableExtract.getColumnModel().getColumn(2).setPreferredWidth(100);
        tableExtract.getColumnModel().getColumn(3).setPreferredWidth(100);

        javax.swing.GroupLayout PanelShowExtractLayout = new javax.swing.GroupLayout(PanelShowExtract);
        PanelShowExtract.setLayout(PanelShowExtractLayout);
        PanelShowExtractLayout.setHorizontalGroup(
            PanelShowExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelShowExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelShowExtractLayout.setVerticalGroup(
            PanelShowExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelShowExtractLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelExtractLayout = new javax.swing.GroupLayout(panelExtract);
        panelExtract.setLayout(panelExtractLayout);
        panelExtractLayout.setHorizontalGroup(
            panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtractLayout.createSequentialGroup()
                        .addComponent(labelChaRev, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(PanelFiltExtr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelExtractLayout.createSequentialGroup()
                        .addComponent(PanelShowExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(separatorExtract)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtractLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valueBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtractLayout.createSequentialGroup()
                                .addComponent(labelBalance)
                                .addGap(167, 167, 167)))))
                .addContainerGap())
        );
        panelExtractLayout.setVerticalGroup(
            panelExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelChaRev, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(PanelFiltExtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelShowExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separatorExtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        valueBalance.setText("R$ " + balance);
        if(balance<0){
            valueBalance.setForeground(Color.red);
        }else if(balance>0){
            valueBalance.setForeground(Color.green);
        }else{
            valueBalance.setForeground(Color.BLACK);
        }

        panelInf.addTab("Extrato", panelExtract);

        panelAnualGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAnualGraphMouseClicked(evt);
            }
        });
        panelAnualGraph.setLayout(new javax.swing.BoxLayout(panelAnualGraph, javax.swing.BoxLayout.LINE_AXIS));

        labelGrapAnual.setText("Anual");
        panelAnualGraph.add(labelGrapAnual);

        buttonGroupFiltGra.add(checkCharGraFilt);
        checkCharGraFilt.setText("Despesas");

        buttonGroupFiltGra.add(chekRevGraFilt);
        chekRevGraFilt.setText("Receitas");

        texDateFromGraFilt.setEnabled(false);

        labeDateSepGraFilt.setText("-");

        texDateUntilGraFilt.setEnabled(false);

        buttonSelecGraFilt.setText("Filtro");

        javax.swing.GroupLayout PanelFiltExtr1Layout = new javax.swing.GroupLayout(PanelFiltExtr1);
        PanelFiltExtr1.setLayout(PanelFiltExtr1Layout);
        PanelFiltExtr1Layout.setHorizontalGroup(
            PanelFiltExtr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltExtr1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkCharGraFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chekRevGraFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checDateGraFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texDateFromGraFilt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labeDateSepGraFilt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texDateUntilGraFilt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSelecGraFilt)
                .addContainerGap())
        );
        PanelFiltExtr1Layout.setVerticalGroup(
            PanelFiltExtr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFiltExtr1Layout.createSequentialGroup()
                .addGroup(PanelFiltExtr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFiltExtr1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(PanelFiltExtr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkCharGraFilt)
                            .addComponent(chekRevGraFilt)
                            .addComponent(checDateGraFilt)))
                    .addGroup(PanelFiltExtr1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelFiltExtr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texDateFromGraFilt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labeDateSepGraFilt)
                            .addComponent(texDateUntilGraFilt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSelecGraFilt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checDateGraFilt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(checDateGraFilt.isSelected()){
                    texDateFromGraFilt.setEnabled(true);
                    texDateUntilGraFilt.setEnabled(true);
                }
                else{
                    texDateFromGraFilt.setEnabled(false);
                    texDateUntilGraFilt.setEnabled(false);
                }
            }
        });
        buttonSelecGraFilt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(checkCharGraFilt.isSelected()){
                    if(checDateGraFilt.isSelected()){
                        filtGraChargDate();
                    }else{
                        filtGraCharg();
                    }
                }else{
                    if(chekRevGraFilt.isSelected()){
                        if(checDateGraFilt.isSelected()){
                            filtGraRevDate();
                        }else{
                            filtGraRev();
                        }
                    }else{
                        if(checDateGraFilt.isSelected()){
                            filtGraDate();
                        }else{
                            JOptionPane.showMessageDialog(null, "Selecione um filtro!");
                        }
                    }
                }
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Graficos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(PanelFiltExtr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelFiltExtr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelReportLayout.createSequentialGroup()
                .addComponent(panelAnualGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAnualGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInf.addTab("Graficos", panelReport);

        labelDate.setText("Data");

        labelValue.setText("Valor");

        buttonAdd.setText("Adicionar");
        buttonAdd.setBorder(null);
        buttonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroupAdd.add(radioButtonCharge);
        radioButtonCharge.setText("Despesa");

        buttonGroupAdd.add(radioButtonRevenue);
        radioButtonRevenue.setText("Receita");

        labelCategory.setText("Categoria");

        labelTitle.setText("Titulo");

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTitle)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addValue)
                    .addComponent(selectCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addDate)
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addComponent(radioButtonCharge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(radioButtonRevenue))
                    .addGroup(panelAddLayout.createSequentialGroup()
                        .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDate)
                            .addComponent(labelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCategory)
                            .addComponent(labelTitle))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonCharge)
                    .addComponent(radioButtonRevenue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        if(radioButtonCharge.isSelected() == false && radioButtonRevenue.isSelected() == false ){
            selectCategory.setEnabled(false);
        }
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(addValue.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Campo Valor vazio");
                }else if(addDate.getText().trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Campo Data vazio");
                }else{
                    if(radioButtonCharge.isSelected() == true){
                        int confirmBox = JOptionPane.showConfirmDialog(null, "salvar DESPESA",null,OK_CANCEL_OPTION);
                        if(confirmBox == JOptionPane.OK_OPTION){
                            buttonConfirmAddChar();
                        }
                    }else if(radioButtonRevenue.isSelected() == true){
                        int confirmBox = JOptionPane.showConfirmDialog(null, "salvar Receita",null,OK_CANCEL_OPTION);
                        if(confirmBox == JOptionPane.OK_OPTION){
                            buttonConfirmAddRev();
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Seleciona o tipo de transação");
                    }
                }
            }
        });
        radioButtonCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategory.removeAllItems();
                List<String> list = listCharCatList();
                for(int i=0;i<list.size();i++){
                    selectCategory.addItem(list.get(i));
                }
                selectCategory.setEnabled(true);
            }
        });
        radioButtonRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCategory.removeAllItems();
                List<String> list = listRevCatList();
                for(int i=0;i<list.size();i++){
                    selectCategory.addItem(list.get(i));
                }

                selectCategory.setEnabled(true);
            }
        });

        buttonExp.setText("Exportar");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(buttonExp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInf)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInf)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonExp)
                .addGap(102, 102, 102))
        );

        buttonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOptionPane.showMessageDialog(null, "Arquivo salvo em: ");
            }
        });

        setSize(new java.awt.Dimension(948, 717));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void addValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addValueActionPerformed
    
    /**
     * Adicionar nova Receita
     */
    private void buttonConfirmAddRev(){
         try {
            // TODO add your handling code here:
            DateFormat format = DateFormat.getDateInstance();
            id += 1;
            double value = Double.parseDouble(addValue.getText());
            String textDate = addDate.getText();
            Date date;
            date = format.parse(textDate);
            RevenueCategory category = listRevenueCategory.get(selectCategory.getSelectedIndex());
            Revenue revenue = new Revenue(id,value,addTitle.getText(),date,category);
            user.add_revenue(revenue);
            balanceUpdate();
            String[] addList = new String[4];
            addList[0]=addTitle.getText();
            addList[2]=addDate.getText();
            addList[1]=category.getName();
            addList[3]=addValue.getText();
            updateListExt(addList);
            addValue.setText(null);
            addDate.setText(null);
            addTitle.setText(null);
            selectCategory.removeAllItems();
            selectCategory.setEnabled(false);
            buttonGroupAdd.clearSelection();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Informe um data no fomato DD/MM/AAAA");
        }
    }
    
    /**
     * Adicionar nova Despesa
     */
    private void buttonConfirmAddChar(){
         try {              
            // TODO add your handling code here:
            DateFormat format = DateFormat.getDateInstance();
            id += 1;
            double value = Double.parseDouble(addValue.getText());
            String textDate = addDate.getText();
            Date date;
            date = format.parse(textDate);
            ChargeCategory category = listChargeCategory.get(selectCategory.getSelectedIndex());;
            Charge charge = new Charge(id,value,addTitle.getText(),date,category);
            user.add_charge(charge);
            balanceUpdate();
            String[] addList = new String[4];
            addList[0]=addTitle.getText();
            addList[2]=addDate.getText();
            addList[1]=category.getName();
            addList[3]=addValue.getText();
            updateListExt(addList);
            addValue.setText(null);
            addDate.setText(null);
            addTitle.setText(null);
            selectCategory.removeAllItems();
            selectCategory.setEnabled(false);
            buttonGroupAdd.clearSelection();
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Informe um data no fomato DD/MM/AAAA");
        }
    }
    private void panelInfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelInfFocusGained
        buildAnualChart();
    }//GEN-LAST:event_panelInfFocusGained

    private void panelAnualGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAnualGraphMouseClicked
        buildAnualChart();
    }//GEN-LAST:event_panelAnualGraphMouseClicked

    /**
     * Lista de categoria de Reciita
     * @return lista de categorias Receita
     */
    public List<RevenueCategory> listRevCatCri(){
        List<RevenueCategory> listCategory = new ArrayList();
        RevenueCategory category;
        category = new RevenueCategory(0,"Bolsa");
        listCategory.add(category);
        category = new RevenueCategory(1,"Freelance");
        listCategory.add(category);
        category = new RevenueCategory(2,"Salário");
        listCategory.add(category);
        category = new RevenueCategory(3,"Outros");
        listCategory.add(category);
        return listCategory;
    }
    
    public List<String> listRevCatList(){
        List<String> listRevCatList = new ArrayList();
        for(int i=0;i<listRevenueCategory.size();i++){
            listRevCatList.add(listRevenueCategory.get(i).getName());
        }
        return listRevCatList;
    }
    

     /**
     * Lista de categoria de Despesa
     * @return lista de categorias Receita
     */
    public List<ChargeCategory> listCharCatCri(){
        List<ChargeCategory> listCategory = new ArrayList();
        ChargeCategory category;
        category = new ChargeCategory(0,"Supermercado");
        listCategory.add(category);
        category = new ChargeCategory(1,"Aluguel");
        listCategory.add(category);
        category = new ChargeCategory(2,"Luz");
        listCategory.add(category);
        category = new ChargeCategory(3,"Água");
        listCategory.add(category);
        category = new ChargeCategory(4,"Telefone");
        listCategory.add(category);        
        category = new ChargeCategory(5,"Internet");
        listCategory.add(category);       
        category = new ChargeCategory(6,"Celular");
        listCategory.add(category);
        category = new ChargeCategory(7,"Outro");
        listCategory.add(category);
        return listCategory;
    }
    
    public List<String> listCharCatList(){
        List<String> listChaCatList = new ArrayList();
        for(int i=0;i<listChargeCategory.size();i++){
            listChaCatList.add(listChargeCategory.get(i).getName());
        }
        return listChaCatList;
    }
    /**
     * Atualização do valor do Saldo 
     */
    public void balanceUpdate(){
        DecimalFormat df = new DecimalFormat("#,###.00");
        balance = user.get_balance();
        valueBalance.setText("R$ " + df.format(balance));
        if(balance<0){
            valueBalance.setForeground(Color.red);
        }else if(balance>0){
            valueBalance.setForeground(Color.green);
        }else{
            valueBalance.setForeground(Color.BLACK);
        }
    }


    /**
     * Chamada de filtro para extrato de Despesa e Data
     */
    public void filtExtChargDate(){
        if(texDateFromExtFilt.getText().trim().equals("") || texDateUntilExtFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromExtFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilExtFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                buttonGroupFiltExt.clearSelection();
                checDateExtFilt.setSelected(false);
                texDateFromExtFilt.setText("");
                texDateUntilExtFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }

    /**
     * Chamada de filtro para extrato de Despesa
     */
    public void filtExtCharg(){
        //
        buttonGroupFiltExt.clearSelection();
    }
    
    /**
     * Chamada de filtro para extrato de Receita e data
     */
    public void filtExtRevDate(){
        if(texDateFromExtFilt.getText().trim().equals("") || texDateUntilExtFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }
        else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromExtFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilExtFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                buttonGroupFiltExt.clearSelection();
                checDateExtFilt.setSelected(false);
                texDateFromExtFilt.setText("");
                texDateUntilExtFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }
    
    /**
     * Chamada de filtro para extrato de Receita
     */
    public void filtExtRev(){
        //
        buttonGroupFiltExt.clearSelection();
    }

    /**
     * Chamada de filtro para extrato de Data
     */
    public void filtExtDate(){
        if(texDateFromExtFilt.getText().trim().equals("") || texDateUntilExtFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromExtFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilExtFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                checDateExtFilt.setSelected(false);
                texDateFromExtFilt.setText("");
                texDateUntilExtFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }

    /**
     * Chamada de filtro para grafico com Despesa e data
     */
    public void filtGraChargDate(){
        if(texDateFromGraFilt.getText().trim().equals("") || texDateUntilGraFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromGraFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilGraFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                buttonGroupFiltGra.clearSelection();
                checDateGraFilt.setSelected(false);
                texDateFromGraFilt.setText("");
                texDateUntilGraFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }

    /**
     * Chamada de filtro para grafico de Despesa
     */
    public void filtGraCharg(){
        //
        buttonGroupFiltGra.clearSelection();        
    }

    /**
     * Chamada de filtro para graficos de Receita e data
     */
    public void filtGraRevDate(){
        if(texDateFromGraFilt.getText().trim().equals("") || texDateUntilGraFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromGraFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilGraFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                buttonGroupFiltGra.clearSelection();
                checDateGraFilt.setSelected(false);
                texDateFromGraFilt.setText("");
                texDateUntilGraFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }

    /**
     * Chamade de filtro para grafico de Receita
     */
    public void filtGraRev(){
        //
        buttonGroupFiltGra.clearSelection();
    }

    /**
     * Chamada de filtro para grafico de Data
     */
    public void filtGraDate(){
        if(texDateFromGraFilt.getText().trim().equals("") || texDateUntilGraFilt.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo de data!");
        }else{
            try {
                DateFormat format = DateFormat.getDateInstance();
                String textDatefrom = texDateFromGraFilt.getText();
                Date datefrom;
                datefrom = format.parse(textDatefrom);
                String textDateUntil = texDateUntilGraFilt.getText();
                Date dateUntil;
                dateUntil = format.parse(textDateUntil);
                //
                checDateGraFilt.setSelected(false);
                texDateFromGraFilt.setText("");
                texDateUntilGraFilt.setText("");
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Informe a data corretamente!");
            }
        }
    }
    
    public void updateListExt(String[] add){

        DefaultTableModel model = (DefaultTableModel) tableExtract.getModel();  
        TableCellRenderer tcr = new Colorir();
        TableColumn column =  tableExtract.getColumnModel().getColumn(3);
        column.setCellRenderer(tcr);
        model.addRow(add);
        column.setCellRenderer(tcr);  
    }

    public void buildAnualChart() {
        DefaultCategoryDataset data = new DefaultCategoryDataset();
        ArrayList<String> last12Months = new ArrayList<String>();
        
        for (int i = -11; i <= 0; i++) {
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(new Date());
            calendar.add(Calendar.MONTH, i);
            last12Months.add(new SimpleDateFormat("MMM").format(calendar.getTime()));
        }
        
        for (String month : last12Months) {
            data.addValue(20, "Saldo", month);
            data.addValue(10, "Custo", month);
            data.addValue(30, "Receita", month);
        }

        JFreeChart chart = ChartFactory.createLineChart(
            "Últimos 12 meses",
            "Meses",
            "R$",
            data,
            PlotOrientation.VERTICAL,
            true, // legend?
            true, // tooltips?
            false // URLs?
        );

        ChartFrame frame = new ChartFrame("My chart", chart);
        frame.pack();
 
        panelAnualGraph.removeAll();
        panelAnualGraph.setPreferredSize(new Dimension(720, 0));
        panelAnualGraph.add(frame.getChartPanel(), BorderLayout.CENTER);
        panelAnualGraph.validate();
   }
    
    private DefaultListModel listModel;
    private User user;
    private double balance;
    int id;
    List<RevenueCategory> listRevenueCategory;
    List<ChargeCategory> listChargeCategory;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFiltExtr;
    private javax.swing.JPanel PanelFiltExtr1;
    private javax.swing.JPanel PanelShowExtract;
    private javax.swing.JTextField addDate;
    private javax.swing.JTextField addTitle;
    private javax.swing.JTextField addValue;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonExp;
    private javax.swing.ButtonGroup buttonGroupAdd;
    private javax.swing.ButtonGroup buttonGroupFiltExt;
    private javax.swing.ButtonGroup buttonGroupFiltGra;
    private javax.swing.ButtonGroup buttonGroupMoreInf;
    private javax.swing.JButton buttonSelecExtFilt;
    private javax.swing.JButton buttonSelecGraFilt;
    private javax.swing.JCheckBox checDateExtFilt;
    private javax.swing.JCheckBox checDateGraFilt;
    private javax.swing.JCheckBox checkCharExtFilt;
    private javax.swing.JCheckBox checkCharGraFilt;
    private javax.swing.JCheckBox chekRevExtFilt;
    private javax.swing.JCheckBox chekRevGraFilt;
    private javax.swing.JFileChooser expFilExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labeDateSepExtFilt;
    private javax.swing.JLabel labeDateSepGraFilt;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelCategory;
    private javax.swing.JLabel labelChaRev;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelGrapAnual;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelValue;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelAnualGraph;
    private javax.swing.JPanel panelExtract;
    private javax.swing.JTabbedPane panelInf;
    private javax.swing.JPanel panelReport;
    private javax.swing.JRadioButton radioButtonCharge;
    private javax.swing.JRadioButton radioButtonRevenue;
    private javax.swing.JComboBox<String> selectCategory;
    private javax.swing.JSeparator separatorExtract;
    private javax.swing.JTable tableExtract;
    private javax.swing.JTextField texDateFromExtFilt;
    private javax.swing.JTextField texDateFromGraFilt;
    private javax.swing.JTextField texDateUntilExtFilt;
    private javax.swing.JTextField texDateUntilGraFilt;
    private javax.swing.JLabel valueBalance;
    // End of variables declaration//GEN-END:variables
}
